package org.example;

public enum BotState {
    START, WAITING1, WAITING2, WAITING3, WAITING4, WAITING5, WAITING6,WAITING7, NOTWAITING, WAITING_AFTER_DAY,WAITING_AFTER_DAY2,REWAITING,WAITINGAFTERADD
}
